#!/usr/bin/env python3
"""Emit each screen's HTML into /tmp/flippergotchi for the preview harness.

The gameplay screens used to be generated by CLI subcommands, but the CLI was
trimmed to `run`/`doctor` -- gameplay is the on-device UI action layer now. So
this drives the sim `run` loop (writes the HUD + encounter/capture frames) and
then calls the in-game action functions in ``flippergotchi.commands`` directly
(each writes its screen's HTML as a side effect), which is exactly what
tools/shoot.py then renders to the device-accurate PNGs.

    python3 tools/gen_preview_html.py     # writes /tmp/flippergotchi/*.html
"""
from __future__ import annotations

import os
import random
import sys

# Run standalone (`python3 tools/gen_preview_html.py`) even when the package
# isn't pip-installed: put the repo root on sys.path.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from flippergotchi import commands as c  # noqa: E402
from flippergotchi.agent import Agent
from flippergotchi.config import Config
from flippergotchi.pet.state import PetState

TICKS = 60


def main() -> None:
    cfg = Config()
    cfg.simulate = True
    cfg.tui = False
    cfg.tick_interval = 0.0     # don't sleep between ticks
    cfg.time_scale = 40.0
    random.seed(7)              # deterministic-ish sample content

    # The pet/scanner loop writes the HUD (face.html) + encounter/capture frames.
    Agent(cfg, PetState(name="Flippy")).run(ticks=TICKS)

    # The rest of the screens come from the in-game action layer -- each cmd_*
    # writes its screen HTML. Guarded so one failing screen doesn't abort the set.
    for fn, args in ((c.cmd_encounter, ()), (c.cmd_feed, (None,)),
                     (c.cmd_achievements, ()), (c.cmd_gear, (None,)),
                     (c.cmd_battle, (None, False))):
        try:
            fn(cfg, *args)
        except Exception as e:  # noqa: BLE001 - best-effort preview generation
            print(f"[preview] {getattr(fn, '__name__', fn)} skipped: {e}")


if __name__ == "__main__":
    main()
